<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;


class PatientDisposal extends BaseController
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function show()
    {

    }

    public function store(Request $request)
    {
        $patientDisposal['patient_id']=request('patient_id');
        $patientDisposal['disposal_date']=request('disposal_date');

        return message('',$patientDisposal,200);
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update()
    {
        return parent::update(); // TODO: Change the autogenerated stub
    }

}
